#!/usr/bin/env zsh

pandoc-tangle --from markdown --to code-maude --code mod-template module-template.md        > src/module-template.maude
pandoc-tangle --from markdown --to code-maude --code univ         universal-construction.md > src/universal-construction.maude
pandoc-tangle --from markdown --to code-maude --code cterm        constrained-terms.md      > src/constrained-terms.maude
pandoc-tangle --from markdown --to code-maude --code msh          msh.md                    > src/msh.maude
pandoc-tangle --from markdown --to code-maude --code vabs         vabs.md                   > src/vabs.maude
pandoc-tangle --from markdown --to code-maude --code intersection intersection.md           > src/intersection.maude
# pandoc-tangle --from markdown --to code-maude --code purification purification.md           > src/purification.maude
# pandoc-tangle --from markdown --to code-maude --code state-space     state-space.md            > src/state-space.maude
