#!/usr/bin/env zsh

pandoc-tangle --from markdown --to code-maude --code msh   msh.md               > msh.maude
pandoc-tangle --from markdown --to code-maude --code cterm constrained-terms.md > cterm.maude
