#!/usr/bin/env zsh

pandoc-tangle --from markdown --to code-maude --code module-template module-template.md        > src/mod-template.maude
pandoc-tangle --from markdown --to code-maude --code module-exp      universal-construction.md > src/univ.maude
pandoc-tangle --from markdown --to code-maude --code cterm           constrained-terms.md      > src/cterm.maude
pandoc-tangle --from markdown --to code-maude --code msh             msh.md                    > src/msh.maude
# pandoc-tangle --from markdown --to code-maude --code state-space     state-space.md            > src/state-space.maude
